## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


## Creating tensors¶
PyTorch loves tensors. So much so there's a whole documentation page dedicated to the torch.Tensor class.

Your first piece of homework is to read through the documentation on torch.Tensor for 10-minutes. But you can get to that later.

In [1]:
# pip install pandas

In [2]:
# pip install matplotlib

In [3]:
# pip install torch torchvision torchaudio -f https://download.pytorch.org/whl/cu117/torch_stable.html

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.0.1


In [5]:
import torch

if torch.cuda.is_available():
    print("GPU is available")
    print("GPU Device Name:", torch.cuda.get_device_name(0))
else:
    print("GPU not available, using CPU")


GPU is available
GPU Device Name: NVIDIA GeForce RTX 3070 Ti


In [6]:
!nvidia-smi 

Mon Jul 31 18:15:19 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.40                 Driver Version: 536.40       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3070 Ti   WDDM  | 00000000:01:00.0  On |                  N/A |
|  0%   39C    P8               4W / 290W |     24MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [7]:
tensor = torch.tensor([[[7, 4],
                        [3, 5]],
                       [[2, 1],
                        [4, 0]],
                       [[1, 9],
                        [9, 8]]])
tensor

tensor([[[7, 4],
         [3, 5]],

        [[2, 1],
         [4, 0]],

        [[1, 9],
         [9, 8]]])

In [8]:
tensor.ndim

3

In [9]:
tensor.shape

torch.Size([3, 2, 2])

### Random tensors

Why random tensors ?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represents the data.
`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [10]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0441, 0.2689, 0.4641, 0.5646],
        [0.8325, 0.5287, 0.4843, 0.4496],
        [0.7761, 0.9407, 0.1796, 0.9338]])

In [11]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [12]:
# Create a tensors of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
zeros.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [14]:
# Use torch.arange()
one_to_hundred = torch.arange(0, 100, step=10)
one_to_hundred

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
# Creating tensors like
hundred_zeros = torch.zeros_like(one_to_hundred)
hundred_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you run into with Pytorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [16]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False) # Wether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [17]:
float_32_tensor.dtype

torch.float32

In [18]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [19]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [20]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [21]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [22]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor


tensor([[0.5677, 0.7403, 0.4379, 0.4109],
        [0.1111, 0.3902, 0.3621, 0.0879],
        [0.8044, 0.7003, 0.3803, 0.2358]])

In [23]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.5677, 0.7403, 0.4379, 0.4109],
        [0.1111, 0.3902, 0.3621, 0.0879],
        [0.8044, 0.7003, 0.3803, 0.2358]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [24]:
# Create a tensor
another_tensor = torch.rand((3, 4), dtype=torch.float16, device="cuda")
another_tensor

tensor([[0.6245, 0.2947, 0.2415, 0.9146],
        [0.0869, 0.2240, 0.4065, 0.8682],
        [0.5059, 0.9922, 0.5220, 0.4370]], device='cuda:0',
       dtype=torch.float16)

### Manipulating tensors (tensors operations)

Tensors operations include:
* Addition
* Multiplication
* Soustraction
* Division
* Matrix multiplication

In [25]:
# Create a tensor and add ten to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [26]:
tensor + tensor.T

C:\Users\User\AppData\Local\Temp\ipykernel_23420\1374036930.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:3575.)
  tensor + tensor.T


tensor([2, 4, 6])

In [27]:
tensor.unsqueeze(1) + tensor.unsqueeze(1).T

tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

In [28]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of multiplication:

1. Element-wise multiplication
2. Matrix multiplication


In [29]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [30]:
# Matrix muliplication
print(tensor, "*", tensor)
print("Equals:", torch.matmul(tensor, tensor))

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor(14)


## Finding the min, max, mean, sum, etc (tensor agregation)

 


In [31]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [32]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [33]:
# Find the mean
x
x.mean(dtype=float), torch.mean(x.type(torch.float32)), x.type(torch.float32).mean(), torch.mean(x, dtype=float)


(tensor(45., dtype=torch.float64),
 tensor(45.),
 tensor(45.),
 tensor(45., dtype=torch.float64))

## Finding the positional min and max


In [34]:
# Find the positional max
max = torch.argmax(x)
max

tensor(9)

In [35]:
# Find the positional min
min = torch.argmin(x)
min

tensor(0)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshaping into a desired shape
* View - Return a view of a tensor at a certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - Remove all `1` dimension from a tensor
* Unsqueeze - Add `1` dimension to a tensor
* Permute - Return a view of the input with dimensions permuted in a certain way

In [36]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [37]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [38]:
# Change the view
z = x.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [39]:
# Changing z changes x
z[:, 2] = 5
z, x

(tensor([[1., 2., 5., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 5., 4., 5., 6., 7., 8., 9.]))

In [40]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x+1, x+2, x+3], dim=1) # Sens d'emplilement en ligne ou en colonne
x_stacked

tensor([[ 1.,  2.,  3.,  4.],
        [ 2.,  3.,  4.,  5.],
        [ 5.,  6.,  7.,  8.],
        [ 4.,  5.,  6.,  7.],
        [ 5.,  6.,  7.,  8.],
        [ 6.,  7.,  8.,  9.],
        [ 7.,  8.,  9., 10.],
        [ 8.,  9., 10., 11.],
        [ 9., 10., 11., 12.]])

In [41]:
# Torch.squeeze()
x = torch.zeros(2, 1, 2, 1, 2)
print(f"Before squeezing: {x.size()}")
y = torch.squeeze(x)
print(f"After squeezing: {y.size()}")
y = torch.squeeze(x, 1)
print(f"After squeezing the second dimension: {y.size()}")

Before squeezing: torch.Size([2, 1, 2, 1, 2])
After squeezing: torch.Size([2, 2, 2])
After squeezing the second dimension: torch.Size([2, 2, 1, 2])


In [42]:
# Torch.unsqueeze()
print(f"Before unsqueezing: {y.size()}")
z = torch.unsqueeze(y, 1)
print(f"After unsqueezing the second dimension: {z.size()}")

Before unsqueezing: torch.Size([2, 2, 1, 2])
After unsqueezing the second dimension: torch.Size([2, 1, 2, 1, 2])


In [43]:
# Torch.permute() - rearranges the dimensions of a target in a specifyed order - return a view
x = torch.permute(z, (1, 0, 2, 4, 3))
x.size()

torch.Size([1, 2, 2, 2, 1])

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.


In [44]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [45]:
# Let's index on our new tensor
x[:,0], x[-1,-1,-1]

(tensor([[1, 2, 3]]), tensor(9))

## PyTorch tensors and NumPy

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.tensor.numpy()`

In [46]:
# NumPy array to tensor
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor 

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [47]:
# Change the value of array, what will this do to `tensor` ?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [48]:
# Tensor to NumPy array
tensor = torch.ones(2, 4)
array = tensor.numpy()
tensor, array

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32))

In [49]:
# Changes the tensor, what happens to Numpy ?
tensor = tensor + 1
tensor, array

(tensor([[2., 2., 2., 2.],
         [2., 2., 2., 2.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

* `Start with random numbers -> tensor operations -> update numbers to try and make them better representations of the data -> again -> again -> again `

In [50]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2099, 0.4804, 0.7687, 0.9511],
        [0.6504, 0.2066, 0.6839, 0.7069],
        [0.2177, 0.6015, 0.4083, 0.4441]])
tensor([[0.3740, 0.4942, 0.5008, 0.0776],
        [0.7085, 0.5357, 0.3643, 0.1440],
        [0.8229, 0.2734, 0.7526, 0.1788]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [51]:
# Let's make some random tensors that are reproducible
# Set the random seed
torch.manual_seed(42)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(42)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html

## Tensors on GPU

In [59]:
# Move tensor to GPU
tensor = torch.tensor([1, 2, 3])
tensor_to_gpu = tensor.to(device="cuda")
tensor_to_gpu

tensor([1, 2, 3], device='cuda:0')

In [62]:
# Moving tensors back to the cpu
tensor_to_cpu = tensor_to_gpu.cpu().numpy()
tensor_to_cpu

array([1, 2, 3], dtype=int64)